/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.sql.*;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author akbar
 */
public class Laporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Laporan
     */
    
    Connection conn;
    Statement cmd;
    ResultSet rs;
    String SQL;
    
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPenjualanBarang = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        Tahun = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        Bulan = new com.toedter.calendar.JMonthChooser();
        jLabel1 = new javax.swing.JLabel();
        btnTotalPendapatan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPenjualanUmur = new javax.swing.JButton();
        btnPenjualanGender = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 188, 5));
        jLabel7.setText("Laporan");

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        btnPenjualanBarang.setBackground(new java.awt.Color(8, 76, 77));
        btnPenjualanBarang.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualanBarang.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualanBarang.setText("Laporan Jumlah Jual Barang");
        btnPenjualanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanBarangActionPerformed(evt);
            }
        });

        btnPenjualan.setBackground(new java.awt.Color(8, 76, 77));
        btnPenjualan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualan.setText("Laporan Penjualan");
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 76, 77));
        jLabel2.setText("Tahun");

        Bulan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 76, 77));
        jLabel1.setText("Bulan");

        btnTotalPendapatan.setBackground(new java.awt.Color(8, 76, 77));
        btnTotalPendapatan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTotalPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalPendapatan.setText("Laporan Total Pendapatan ");
        btnTotalPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPendapatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPenjualanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tahun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPenjualanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        btnPenjualanUmur.setBackground(new java.awt.Color(8, 76, 77));
        btnPenjualanUmur.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualanUmur.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualanUmur.setText("Laporan Penjualan Berdasarkan Umur");
        btnPenjualanUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanUmurActionPerformed(evt);
            }
        });

        btnPenjualanGender.setBackground(new java.awt.Color(8, 76, 77));
        btnPenjualanGender.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPenjualanGender.setForeground(new java.awt.Color(255, 255, 255));
        btnPenjualanGender.setText("Laporan Penjualan Berdasarkan Gender");
        btnPenjualanGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPenjualanGender, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPenjualanUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btnPenjualanUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPenjualanGender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("bulan", Bulan.getMonth() + 1);
            hash.put("tahun", Tahun.getYear());
            
            File Penjualan = new File("src/UAS/Laporan/Penjualan.jasper");
            JasperPrint JP = JasperFillManager.fillReport(Penjualan.getPath(), hash, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnPenjualanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanBarangActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("bulan", Bulan.getMonth()  + 1);
            hash.put("tahun", Tahun.getYear());
                        
            File Penjualan = new File("src/UAS/Laporan/Jumlah_Jual.jasper");
            JasperPrint JP = JasperFillManager.fillReport(Penjualan.getPath(), hash, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanBarangActionPerformed

    private void btnPenjualanUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanUmurActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
            
            File Penjualan = new File("src/UAS/Laporan/Penjualan_Umur.jasper");
            JasperPrint JP = JasperFillManager.fillReport(Penjualan.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanUmurActionPerformed

    private void btnPenjualanGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanGenderActionPerformed
        // TODO add your handling code here:
        try {
            conn = Koneksi.getKoneksi();
                        
            File Penjualan = new File("src/UAS/Laporan/Penjualan_Gender.jasper");
            JasperPrint JP = JasperFillManager.fillReport(Penjualan.getPath(), null, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnPenjualanGenderActionPerformed

    private void btnTotalPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPendapatanActionPerformed
        // TODO add your handling code here:
            try {
            conn = Koneksi.getKoneksi();
            
            HashMap hash = new HashMap(2);
            hash.put("Bulan", Bulan.getMonth()  + 1);
            hash.put("Tahun", Tahun.getYear());
                        
            File Pendapatan = new File("src/UAS/Laporan/LaporanPendapatan.jasper");
            JasperPrint JP = JasperFillManager.fillReport(Pendapatan.getPath(), hash, conn);
            JasperViewer.viewReport(JP, false);
            
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_btnTotalPendapatanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JMonthChooser Bulan;
    private com.toedter.calendar.JYearChooser Tahun;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnPenjualanBarang;
    private javax.swing.JButton btnPenjualanGender;
    private javax.swing.JButton btnPenjualanUmur;
    private javax.swing.JButton btnTotalPendapatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
