/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

/**
 *
 * @author akbar
 */
public class MainProject extends javax.swing.JFrame {

    /**
     * Creates new form MainProject
     */
    
    Pegawai pegawai;
    Pelanggan pelanggan;
    Barang barang;
    Penjualan penjualan;
    Pembayaran pembayaran;
    Laporan laporan;
    MenuUtama menu;
    
    public MainProject() {
        initComponents();
        
        pegawai = new Pegawai();
        pelanggan = new Pelanggan();
        barang = new Barang();
        penjualan = new Penjualan();
        pembayaran = new Pembayaran();
        laporan = new Laporan();
        menu = new MenuUtama();
        
        if (!menu.isVisible()) {
            jDesktopPane1.add(menu);
            menu.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMenu.setBackground(new java.awt.Color(38, 42, 65));
        btnMenu.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(43, 123, 123));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_dashboard_layout_48px.png"))); // NOI18N
        btnMenu.setText("Menu Utama");
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnPegawai.setBackground(new java.awt.Color(38, 42, 65));
        btnPegawai.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnPegawai.setForeground(new java.awt.Color(43, 123, 123));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_staff_48px.png"))); // NOI18N
        btnPegawai.setText("Pegawai");
        btnPegawai.setBorder(null);
        btnPegawai.setContentAreaFilled(false);
        btnPegawai.setName("btnPegawai"); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });

        btnPelanggan.setBackground(new java.awt.Color(38, 42, 65));
        btnPelanggan.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(43, 123, 123));
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_user_48px.png"))); // NOI18N
        btnPelanggan.setText("Pelanggan");
        btnPelanggan.setBorder(null);
        btnPelanggan.setContentAreaFilled(false);
        btnPelanggan.setName("btnPelanggan"); // NOI18N
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnBarang.setBackground(new java.awt.Color(38, 42, 65));
        btnBarang.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnBarang.setForeground(new java.awt.Color(43, 123, 123));
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_package_48px.png"))); // NOI18N
        btnBarang.setText("Barang");
        btnBarang.setBorder(null);
        btnBarang.setContentAreaFilled(false);
        btnBarang.setName("btnBarang"); // NOI18N
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnPembayaran.setBackground(new java.awt.Color(38, 42, 65));
        btnPembayaran.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnPembayaran.setForeground(new java.awt.Color(43, 123, 123));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_mobile_payment_48px.png"))); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.setBorder(null);
        btnPembayaran.setContentAreaFilled(false);
        btnPembayaran.setName("btnPembayaran"); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        btnPenjualan.setBackground(new java.awt.Color(38, 42, 65));
        btnPenjualan.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnPenjualan.setForeground(new java.awt.Color(43, 123, 123));
        btnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_shopping_cart_48px.png"))); // NOI18N
        btnPenjualan.setText("Penjualan");
        btnPenjualan.setBorder(null);
        btnPenjualan.setContentAreaFilled(false);
        btnPenjualan.setName("btnPenjualan"); // NOI18N
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(38, 42, 65));
        btnLaporan.setFont(new java.awt.Font("Roboto", 1, 21)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(43, 123, 123));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Icon/icons8_graph_report_48px.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorder(null);
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setName("btnLaporan"); // NOI18N
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addGap(18, 18, 18)
                .addComponent(btnPegawai)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan)
                .addGap(18, 18, 18)
                .addComponent(btnBarang)
                .addGap(18, 18, 18)
                .addComponent(btnPenjualan)
                .addGap(18, 18, 18)
                .addComponent(btnPembayaran)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnPegawai)
                    .addComponent(btnPelanggan)
                    .addComponent(btnBarang)
                    .addComponent(btnPembayaran)
                    .addComponent(btnPenjualan)
                    .addComponent(btnLaporan))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 60));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1280, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!menu.isVisible()) {
            jDesktopPane1.add(menu);
            menu.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            penjualan.dispose();
            pembayaran.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pegawai.isVisible()) {
            jDesktopPane1.add(pegawai);
            pegawai.setVisible(true);
            penjualan.dispose();
            pembayaran.dispose();
            pelanggan.dispose();
            barang.dispose();
            menu.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pelanggan.isVisible()) {
            jDesktopPane1.add(pelanggan);
            pelanggan.setVisible(true);
            pegawai.dispose();
            barang.dispose();
            penjualan.dispose();
            pembayaran.dispose();
            menu.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!barang.isVisible()) {
            jDesktopPane1.add(barang);
            barang.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            penjualan.dispose();
            pembayaran.dispose();
            menu.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!pembayaran.isVisible()) {
            jDesktopPane1.add(pembayaran);
            pembayaran.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            penjualan.dispose();
            menu.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!penjualan.isVisible()) {
            jDesktopPane1.add(penjualan);
            penjualan.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            pembayaran.dispose();
            menu.dispose();
            laporan.dispose();
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        if (!laporan.isVisible()) {
            jDesktopPane1.add(laporan);
            laporan.setVisible(true);
            pegawai.dispose();
            pelanggan.dispose();
            barang.dispose();
            pembayaran.dispose();
            menu.dispose();
        }
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
